
-- TABLE STRUCTURE FOR: USERS

CREATE TABLE `USERS` (
  `USER_INTERNAL_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `USER_EXTERNAL_ID` bigint(20) unsigned NOT NULL,
  `USER_EMAIL_ADDRESS` varchar(255) NOT NULL,
  `USER_FULL_NAME` varchar(256) NOT NULL,
  `USER_ROLE` varchar(10) NOT NULL,
  PRIMARY KEY (`USER_INTERNAL_ID`),
  UNIQUE KEY `USER_INTERNAL_ID` (`USER_INTERNAL_ID`),
  UNIQUE KEY `USER_EXTERNAL_ID` (`USER_EXTERNAL_ID`),
  UNIQUE KEY `USER_EMAIL_ADDRESS` (`USER_EMAIL_ADDRESS`),
  UNIQUE KEY `USER_EMAIL_ADDRESS_2` (`USER_EMAIL_ADDRESS`),
  UNIQUE KEY `USER_EMAIL_ADDRESS_3` (`USER_EMAIL_ADDRESS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

